### ISSUE TITLE
大佬我想问一下，你说的核显不能驱动输出，意思是装这个必须要有独立显卡输出才行吗

### ISSUE THREAD

**Issue by WinKaWong** [liu976336402/NUC9-hackintosh#12]

**Comment by WinKaWong** [comment]
核显不能直接接显示器输出信号吗

**Comment by Const-Time** [comment]
可以输出，我用核显hdmi接口睡眠唤醒有问题，换了6600xt就没问题了

**Comment by liu976336402** [comment]
可以的 6600xt的efi 因为注入的缓冲帧不是直接输出的缓冲帧 所以不能用于显示输出 可以用于计算，uhd630的配置文件是可以用核显输出信号的

**Comment by WinKaWong** [comment]
感谢您的付出和贡献，因为有您我现在已经用上了蒙特雷12.6了，6600xt也插入了。所以说大佬您的引导能无痛升级13.0吗？后续想要用随航功能，打钱转接固态接口安装一个博通网卡。想问一下是直接装上就可以了吗，需要屏蔽ax200吗？Aries在 2022年10月22日，22:17，ccdeskde ***@***.***> 写道：﻿
可以的 6600xt的efi 因为注入的缓冲帧不是直接输出的缓冲帧 所以不能用于显示输出 可以用于计算，uhd630的配置文件是可以用核显输出信号的

**Comment by liu976336402** [comment]
刚刚已经升级到opencore 0.8.5了 系统也ota升级到Ventura了，但是升级上来感觉不如12.6流畅 而且网卡之类的暂时还没测试

**Comment by rocky930215** [comment]
> 刚刚已经升级到opencore 0.8.5了 系统也ota升级到Ventura了，但是升级上来感觉不如12.6流畅 而且网卡之类的暂时还没测试

期待测试下有没有问题
