### ISSUE TITLE
卡BE 界面

### ISSUE THREAD

**Issue by brookeke** [liu976336402/NUC9-hackintosh#13]
我机子装的6650xt品卡已经用了b站的方法伪装了并加到efi中但是我安装还是卡BE
我对这网上的教程设置了好几回还是没办法，唯一一次成功了抹除硬盘后第一次重启以后自动启动win后又卡be然后就回不去了🥹

**Comment by liu976336402** [comment]
我这边能给的建议是先在bios中设置使用核显 用uhd630的配置文件 先安装系统 能稳定运行后 在对6650xt进行仿冒和完善

**Comment by brookeke** [comment]
好的我明天再试试，非常感谢🙏
