### ISSUE TITLE
可以在这里谈论nuc9相关问题

### ISSUE THREAD

**Issue by yufeie** [liu976336402/NUC9-hackintosh#14]
可以在这里谈论nuc9相关问题

_Originally posted by @liu976336402 in https://github.com/liu976336402/NUC9-hackintosh/discussions/9_
    刚玩这个不懂，红眼的机子，后置音频没有声音输出不知道为什么。

**Comment by liu976336402** [comment]
启动参数里面有alcid 自行更换测试
