### ISSUE TITLE
NUC9红眼U盘启动后选择macOS install 卡在logo页面，无进度条

### ISSUE THREAD

**Issue by huwfLove** [liu976336402/NUC9-hackintosh#15]

**Comment by liu976336402** [comment]
> _No description provided._

使用的哪一份efi 安装的什么系统 启动参数加 -v把卡住的代码发上来

**Comment by huwfLove** [comment]
使用的EFI-UHD630，安装macOS Monterey 12.5.1 (21G83) by macOShome.dmg
-v参数在哪增加呢？macos Install前使用快捷键win+v没生效。

**Comment by huwfLove** [comment]
![Uploading image.png…]()

**Comment by liu976336402** [comment]
> ![Uploading image.png…]()
> 

readme里面有群号，可以来群里求助

**Comment by liu976336402** [comment]
> ![Uploading image.png…]()
> 

uhd630 efi 直接安装需要稍微修改下显卡的缓冲帧，安装完成后再改回来

**Comment by huwfLove** [comment]
好的，感谢
