### ISSUE TITLE
13.0直接安装以后双网口只有一个能用

### ISSUE THREAD

**Issue by 1314mjf521** [liu976336402/NUC9-hackintosh#16]
13.0直接安装以后双网口只有一个能用，有没有大佬提供个思路看看是哪里的问题

**Comment by 1314mjf521** [comment]
> 13.0直接安装以后双网口只有一个能用，有没有大佬提供个思路看看是哪里的问题
型号：NUC9-I9-9980HK  骨伽DNF联名款

**Comment by liu976336402** [comment]
> > 13.0直接安装以后双网口只有一个能用，有没有大佬提供个思路看看是哪里的问题
> 型号：NUC9-I9-9980HK  骨伽DNF联名款
> 

13代删除了i210的驱动，所以需要oc注入相关kext，群里有我上传的，可以加群，亦或是找个12系统的mac自行拷贝
