### ISSUE TITLE
是否支持隔空投送功能呢？

### ISSUE THREAD

**Issue by monkeying-boy** [liu976336402/NUC9-hackintosh#3]
想要问一下这套EFI支持隔空投送吗？

**Comment by liu976336402** [comment]
理论上来说 应该是可以的 但是还需要自行测试

**Comment by brookeke** [comment]
作者你好，隔空投送还有随航功能需要自己再安装黑苹果网卡对吗

**Comment by liu976336402** [comment]
隔空投送的话，使用英特尔的无线网卡应该也是可以的，但是无线随航功能就需要自行更换白苹果的无线网卡了

**Comment by brookeke** [comment]
谢谢😄我购买了白苹果网卡，还没到货，我主要怕板载网卡和白苹果网卡冲突。不知道怎么有没有处理方法。

**Comment by liu976336402** [comment]
并不冲突 只需要把intel相关网卡的kext去掉，然后添加相关白苹果网卡的kext即可

**Comment by brookeke** [comment]
非常感谢，到时候到货了试试🤝
