### ISSUE TITLE
请问 nuc9 i9 相关问题

### ISSUE THREAD

**Issue by MalsonQu** [liu976336402/NUC9-hackintosh#5]
您好我想请教一些问题
我的是nuc9i9 使用的白苹果的网卡 公版5700 重新安装的 big sur 现在有以下几个问题
- 蓝牙默认打开 但是无法关闭(蒙特雷下蓝牙不可用(已使用buletoolFixup))
- 隔空投送 只能向其他设备发送 无法接收
- hackintool VDA解码器 解码失败
- 开机后 3-5分钟概率冻屏卡死
- 有线随行黑屏
- 无线随行无法找到设备
或者可否留个联系方式 我愿意付费请您帮我解决一下 我的问题

**Comment by MalsonQu** [comment]
解决了。。。 还是usb定制的问题，时间紧 我这边直接用 USBInjectAll 先对付用用

然后无法硬解是需要在bios 中 devices->video->igpu 从 auto 改成 enable 不然好像是默认把核显屏蔽了

**Comment by liu976336402** [comment]
刚刚看到 解决了就好

**Comment by MalsonQu** [comment]
感谢大佬 我重新看了 您的USBports.kext 导入到 hackintool 发现 有部分名称HS开头的usb的端口 连接器为usb3 (这里 我下载下来看到有部分是 usb3 然后 修改后重启后这个无法复现了) 我将其修改为usb2 导出并拖入到efi文件夹下 重新启动 一切正常

**Comment by MalsonQu** [comment]
HS12 和 HS14 为白果的网卡 蓝牙usb端口 物理位置为 计算卡 上方的那个usb2.0口 必须设置成 usb2 设置成 internal 会导致 启动后冻屏死机

**Comment by liu976336402** [comment]
这个还真没有注意 感谢提出 有时间我会把这个加到文档里面

**Comment by rocky930215** [comment]
能否分享下重新定制的usb？我也是之前问了好久大佬这个efi白苹果网卡的事

**Comment by MalsonQu** [comment]
@rocky930215 好的 我试试提交一个rp

**Comment by rocky930215** [comment]
> @rocky930215 好的 我试试提交一个rp
> 
> 

非常感谢，晚点试试。但是是11.7完美可用是吧？我是跑的12.6

**Comment by MalsonQu** [comment]
@rocky930215 我这边 11.7完美可用 
以下均正常
- 隔空投送 
- 无线随行 
- 二代触控板 
- 二代蓝牙键盘 
- 苹果耳机 
使用的白果卡型号是 `bcm943602cs` 你是 12.6 的话 记得加载 `bluetoolFixup.kext` 期待你的反馈

**Comment by rocky930215** [comment]
@MalsonQu 这个usb定制试了一下，12.6下配合大佬的efi完美驱动白果网卡的蓝牙WIFI。白果卡型号忘了，自己13 mbp里拆出来的。但是12.6下测试，隔空投送还是有问题，隔空投送界面下能看到其他设备但是点击以后没反应

**Comment by rocky930215** [comment]
@MalsonQu @liu976336402 更正一下，隔空投送手机到电脑没有任何问题，但是电脑分享到手机是点击无反应

**Comment by rocky930215** [comment]
隔空这个问题正常驱动英特尔网卡也是一样的，希望试一下，看看能不能解决

**Comment by MalsonQu** [comment]
@rocky930215 我刚刚装好11.7系统之后也是点击手机无反应,手机能投到电脑上,mac重新登录AppleID也不行,后来不知道咋的 自己又好了 或者你再等等看试试?[doge]

**Comment by Const-Time** [comment]
@rocky930215 请问你有随机冻屏的问题吗，我这个好频繁😭

**Comment by rocky930215** [comment]
> @rocky930215 请问你有随机冻屏的问题吗，我这个好频繁😭

这个冻屏指的是？？

我有这么几个随机问题，开机随机出现引导之后啰嗦模式跑完，显卡点不亮，只能强制重启。这个问题以前用自己配的efi和别人分享的也遇到过，后来发现点不亮情况出现以后，不关机一状态下显卡换一个dp口接显示器就正常了，但是那时候用的5500显卡，现在用6600实测是换口也不行，只能强制关机重启解决。

另外就是确实会系统内出现随机黑屏的情况，黑了就亮不了了，类似于老的白苹果mbp换nvme硬盘睡死状态，也确实是系统内节能设置关闭屏幕改成永不就没再出现过这个问题，不好说是显卡这块的事还是硬盘的事…

其余暂时可以说都解决了。网卡不能隔空，我看是12通病，不论网卡型号。git里有人讨论过，官方也是说暂时无解。雷电3万兆网卡能识别能加载，就是连不上，这个好像也和网卡型号有关系…aqc107苹果做了一定屏蔽，不好说啥情况…

**Comment by Const-Time** [comment]
> > @rocky930215 请问你有随机冻屏的问题吗，我这个好频繁😭
> 
> 这个冻屏指的是？？
> 
> 我有这么几个随机问题，开机随机出现引导之后啰嗦模式跑完，显卡点不亮，只能强制重启。这个问题以前用自己配的efi和别人分享的也遇到过，后来发现点不亮情况出现以后，不关机一状态下显卡换一个dp口接显示器就正常了，但是那时候用的5500显卡，现在用6600实测是换口也不行，只能强制关机重启解决。
> 
> 另外就是确实会系统内出现随机黑屏的情况，黑了就亮不了了，类似于老的白苹果mbp换nvme硬盘睡死状态，也确实是系统内节能设置关闭屏幕改成永不就没再出现过这个问题，不好说是显卡这块的事还是硬盘的事…
> 
> 其余暂时可以说都解决了。网卡不能隔空，我看是12通病，不论网卡型号。git里有人讨论过，官方也是说暂时无解。雷电3万兆网卡能识别能加载，就是连不上，这个好像也和网卡型号有关系…aqc107苹果做了一定屏蔽，不好说啥情况…

就是开机一会儿，屏幕就卡死在当前的画面上，只能强制关机才行，不然一直卡在那里

**Comment by Const-Time** [comment]
@rocky930215 我换了口子已经解决了，升级到13，隔空投送已经可以投送给手机了

**Comment by rocky930215** [comment]
> @rocky930215 我换了口子已经解决了，升级到13，隔空投送已经可以投送给手机了

换dp口了？

**Comment by Const-Time** [comment]
> > @rocky930215 我换了口子已经解决了，升级到13，隔空投送已经可以投送给手机了
> 
> 换dp口了？

 换了m2转白苹果网卡要接的接口，我电脑死机就是因为这个影响的，感觉你要重新定制下usb，我重新定制后，隔空投送就正常了，不应该是升级到13才好的

**Comment by rocky930215** [comment]
你的m2转接卡接到了机箱里哪个m2接口？机身里一共3个对吧

**Comment by Const-Time** [comment]
我的的nc100，不是石英峡谷，只有两个，我用的远离cpu那个，主要是改了转接卡的线插的4根针的口子

**Comment by rocky930215** [comment]
> 我的的nc100，不是石英峡谷，只有两个，我用的远离cpu那个，主要是改了转接卡的线插的4根针的口子

那不对啊… nc100不就是机箱 电源的差别吗？我还差点入了一个机箱，卖的人把我劝退了…号称电源不稳定，是这样吗……？现在也没货了好像。

方便时候分享我一个你重新定制的usbport.kext，我直接试一下看看有没有改善。

**Comment by Const-Time** [comment]
> > 我的的nc100，不是石英峡谷，只有两个，我用的远离cpu那个，主要是改了转接卡的线插的4根针的口子
> 
> 那不对啊… nc100不就是机箱 电源的差别吗？我还差点入了一个机箱，卖的人把我劝退了…号称电源不稳定，是这样吗……？现在也没货了好像。
> 
> 方便时候分享我一个你重新定制的usbport.kext，我直接试一下看看有没有改善。

电源不稳定我感觉不出来，没拿来打游戏，nc100的m.2口子只有计算卡那里的两个，下面那个转接板也只有两根pcie插槽，usbport.kext下班回家我发你

**Comment by rocky930215** [comment]
> > > 我的的nc100，不是石英峡谷，只有两个，我用的远离cpu那个，主要是改了转接卡的线插的4根针的口子
> 
> > 
> 
> > 那不对啊… nc100不就是机箱 电源的差别吗？我还差点入了一个机箱，卖的人把我劝退了…号称电源不稳定，是这样吗……？现在也没货了好像。
> 
> > 
> 
> > 方便时候分享我一个你重新定制的usbport.kext，我直接试一下看看有没有改善。
> 
> 
> 
> 电源不稳定我感觉不出来，没拿来打游戏，nc100的m.2口子只有计算卡那里的两个，下面那个转接板也只有两根pcie插槽，usbport.kext下班回家我发你

感谢！我实在懒得一个口一个口试去定制……

**Comment by Const-Time** [comment]
> > > > 我的的nc100，不是石英峡谷，只有两个，我用的远离cpu那个，主要是改了转接卡的线插的4根针的口子
> > 
> > 
> > > 
> > 
> > 
> > > 那不对啊… nc100不就是机箱 电源的差别吗？我还差点入了一个机箱，卖的人把我劝退了…号称电源不稳定，是这样吗……？现在也没货了好像。
> > 
> > 
> > > 
> > 
> > 
> > > 方便时候分享我一个你重新定制的usbport.kext，我直接试一下看看有没有改善。
> > 
> > 
> > 电源不稳定我感觉不出来，没拿来打游戏，nc100的m.2口子只有计算卡那里的两个，下面那个转接板也只有两根pcie插槽，usbport.kext下班回家我发你
> 
> 感谢！我实在懒得一个口一个口试去定制……

10几分钟就定制好了，本来这个口也不多，我怎么发你呢

**Comment by rocky930215** [comment]
@Const-Time 刚刚又试了一下，果然如@MalsonQu所说，他分享的usbport要等他自己过一阵就行了。。。实在是不太懂什么原理，但是确实他分享这个我现在用实现双向airdrop了，很神奇

**Comment by Const-Time** [comment]
> @Const-Time 刚刚又试了一下，果然如@MalsonQu所说，他分享的usbport要等他自己过一阵就行了。。。实在是不太懂什么原理，但是确实他分享这个我现在用实现双向airdrop了，很神奇

那就好，估计你们两个用的口是同一个，我换了口就必须重新定制了

**Comment by rocky930215** [comment]
@liu976336402 大佬这是更新0.8.5了吗？跑的了13不

**Comment by liu976336402** [comment]
> @liu976336402 大佬这是更新0.8.5了吗？跑的了13不

想要跑13不用更新至0.8.5 前面的0.8.3已经可以运行预览版的13了

**Comment by rocky930215** [comment]
> > @liu976336402 大佬这是更新0.8.5了吗？跑的了13不
> 
> 
> 
> 想要跑13不用更新至0.8.5 前面的0.8.3已经可以运行预览版的13了

那这个085相当于例行升级？

**Comment by liu976336402** [comment]
刚刚才发现有13的推送了，那建议还是升级到0.8.5来运行13

**Comment by rocky930215** [comment]
这个085在12.6完美，结果手贱…直接ota的13，一通跑码，直接挂了…完全跑不起来了…引导报了好多错，一开始直接检测不到硬盘里的oc启动项，u盘引导也看不到。后来好歹是又看到了，但是始终跑不起来

**Comment by Const-Time** [comment]
> 这个085在12.6完美，结果手贱…直接ota的13，一通跑码，直接挂了…完全跑不起来了…引导报了好多错，一开始直接检测不到硬盘里的oc启动项，u盘引导也看不到。后来好歹是又看到了，但是始终跑不起来

kext你都升级到最新版呢，我升级到13没啥问题。

**Comment by rocky930215** [comment]
我就是直接套用分享出来的085，按我之前的改了设置，换三码。结果ota跑完升级程序就跑不起来了

**Comment by rocky930215** [comment]
@liu976336402 ![image](https://user-images.githubusercontent.com/61199898/198494631-c46e21ba-9808-468f-b8dd-a90cdf1c4875.jpeg)

大佬麻烦给看下…我现在已经完全跑不起来了…

全新安装Ventura，用了你的085，只改3码，不启用AppleALC，删除相关启动项，其他什么都没动的情况下，引导先报这个错，然后再跑一大段就自己重启…

**Comment by liu976336402** [comment]
是使用intel的无限网卡吗

**Comment by liu976336402** [comment]
Misc -> Debug -> Target 设置成10进制67 或者 16进制 0x43 然后启动会生成日志文件 把它给我看一下

**Comment by rocky930215** [comment]
@liu976336402 

[opencore-2022-10-28-064339.txt](https://github.com/liu976336402/NUC9-hackintosh/files/9885961/opencore-2022-10-28-064339.txt)

麻烦给看下

**Comment by liu976336402** [comment]
> @liu976336402
> 
> [opencore-2022-10-28-064339.txt](https://github.com/liu976336402/NUC9-hackintosh/files/9885961/opencore-2022-10-28-064339.txt)
> 
> 麻烦给看下

https://github.com/OpenIntelWireless/itlwm/releases/download/v2.2.0-alpha/AirportItlwm-Ventura-v2.2.0-DEBUG-alpha-ee56708.zip 下载这个 替换efi/kext 下面的airportitlwm.kext 清理nvram 重新启动

**Comment by rocky930215** [comment]
好的我试下。只是这个kext更新了造成的？你那边分享的不是直接就能在你机器上正常引导…之前我试着不注入intel网卡，跑白果网卡也是一样的跑不起来

**Comment by liu976336402** [comment]
> 好的我试下。只是这个kext更新了造成的？你那边分享的不是直接就能在你机器上正常引导…之前我试着不注入intel网卡，跑白果网卡也是一样的跑不起来

看日志文件除了这个以外，其他的和我的启动日志并没有什么不同

**Comment by liu976336402** [comment]
> 好的我试下。只是这个kext更新了造成的？你那边分享的不是直接就能在你机器上正常引导…之前我试着不注入intel网卡，跑白果网卡也是一样的跑不起来

而且我在readme文档中已经写上了 ，更新13需要将intel网卡的kext更新 所以0.8.5中的知只是opencore0.8.5 Montery12.6的efi，想要运行13 就要更新这个kext
