### ISSUE TITLE
长时间睡眠唤醒绿屏

### ISSUE THREAD

**Issue by Const-Time** [liu976336402/NUC9-hackintosh#6]
使用核显，长时间睡眠后唤醒绿屏，使用独显会有这个问题吗，我打算入张6600xt

**Comment by liu976336402** [comment]
我现在是用独显 没有这个问题 但是理论上来说 使用核显也不应该出现这个问题

**Comment by Const-Time** [comment]
那你会有长时间睡眠直接睡死的情况吗

**Comment by liu976336402** [comment]
没有 我都是整晚不关机的 第二天唤醒依旧没问题

**Comment by Const-Time** [comment]
你是用的dp接口接的显示器吗，我怀疑是我用的hdmi的原因

**Comment by liu976336402** [comment]
是的 ，dp接口 我这个用hdmi启动的时候 -v直接不显示任何日志 后来改用的dp接口
