### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by balabalabiu** [liu976336402/NUC9-hackintosh#7]
大佬，我使用gibMacOS制作macOS Catalina 10.15.7的恢复U盘，替换EFI-HD630后，提示Prelinked injection AirportItlwm.kext。
请问可以给一些建议么？或者有推荐安装流程么，感谢

**Comment by liu976336402** [comment]
英特尔无线网卡的kext是不同系统专用的，https://github.com/OpenIntelWireless/itlwm/releases 在这里面找到对应你系统版本的kext

**Comment by balabalabiu** [comment]
来信已收到

**Comment by balabalabiu** [comment]
我替换Catalina版本的kext但仍重启，想咨询下当前的EFI是大佬你升级Monterey之后的文件是么？若使用macOS Catalina安装的话就需要修改一些文件。请问您方便安利下最初安装的方案么？

**Comment by liu976336402** [comment]
github上面有个11的仓库在，只需要搜索nuc9 hackintosh有个外国友人的仓库是bigsur的efi

**Comment by balabalabiu** [comment]
好滴，我再学习学习，灰常感谢。

**Comment by balabalabiu** [comment]
> 加上-v参数看看卡到哪里，具体看代码才知道是哪里出现的问题

OK，加上排查了几个日志，之后有空在研究研究。
